name: "Fan out plugin updates"

on:
  push:
    branches:
      - main

jobs:
  notify:
    name: "Trigger plugin updates"
    uses: KL-Engineering/central-microgateway-configuration/.github/workflows/sync-plugin.yaml@main
    with:
      github-repository-name: ${{ github.event.repository.name }}
      tag: ${GITHUB_SHA::7}
    secrets:
      github-token: ${{ secrets.GATEWAY_CONFIG_SYNC_BOT }}
